version: "3.6"
services:
  registry:
    image: "registry:2"
    restart: always
    ports:
      - 5000:5000
    environment:
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry_data:/var/lib/registry
      # - /path/certs:/certs
      - ./auth:/auth
volumes:
  registry_data:
    name: registry_data
