version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - postgres.env
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - database

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  db_postgres_data:
    name: db_postgres_data

networks:
  database:
    name: database
