version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - postgres.env
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_postgres_data:
