version: "3.8"

services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - wakapi-data:/data
    networks:
      - database

volumes:
  wakapi-data:
    name: wakapi-data

networks:
  database:
    name: database
    external: true
