POST https://auth0.openai.com/oauth/token
content-type: application/json

{
    "redirect_uri": "com.openai.chat://auth0.openai.com/ios/com.openai.chat/callback",
    "grant_type": "authorization_code",
    "client_id": "pdlLIX2Y72MIl2rhLhTE9VV9bN905kBh",
    "code": $YOUR_CODE,
    "code_verifier": "IkrrBD89CBmwwzM-csfBnWKLMan5uE7laCMd2YTcPWE"
}